export const DB_NAME = "ecommerce";

export const USER_TEMPORARY_TOKEN_EXPIRY = 20 * 60 * 1000; // 20 minutes

export const MAXIMUM_SUB_IMAGE_COUNT = 10;

/**
 * @type {{ FLAT:"FLAT"; } as const}
 */
export const CouponTypeEnum = {
  FLAT: "FLAT",
  PERCENTAGE: "PERCENTAGE",
};

export const AvailableCouponTypes = Object.values(CouponTypeEnum);

/**
 * @type {{ PENDING: "PENDING"; CANCELLED: "CANCELLED"; DELIVERED: "DELIVERED" } as const}
 */
export const OrderStatusEnum = {
  PENDING: "PENDING",
  CANCELLED: "CANCELLED",
  DELIVERED: "DELIVERED",
  HOLD: "HOLD",
  COMPLETED: "COMPLETED",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  REFUNDED: "REFUNDED",
  ON_HOLD: "ON_HOLD",
  PARTIALLY_SHIPPED: "PARTIALLY_SHIPPED",
};

export const AvailableOrderStatuses = Object.values(OrderStatusEnum);

export const EnquiryStatusEnum = {
  SUBMITTED: "SUBMITTED",
  PENDING: "PENDING",
  AWAITING_RESPONSE: "AWAITING_RESPONSE",
  IN_PROGRESS: "IN_PROGRESS",
  ON_HOLD: "ON_HOLD",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
  CLOSED: "CLOSED",
  ARCHIVED: "ARCHIVED",
};

export const AvailableEnquiryStatuses = Object.values(EnquiryStatusEnum);

/**
 * @type {{ UNKNOWN:"UNKNOWN"; RAZORPAY: "RAZORPAY"; PAYPAL: "PAYPAL"; } as const}
 */
export const PaymentProviderEnum = {
  UNKNOWN: "UNKNOWN",
  RAZORPAY: "RAZORPAY",
  PAYPAL: "PAYPAL",
  COD: "COD",
};

export const paypalBaseUrl = {
  sandbox: "https://api-m.sandbox.paypal.com",
};

export const AvailablePaymentProviders = Object.values(PaymentProviderEnum);

/**
 * @type {{ GOOGLE: "GOOGLE"; GITHUB: "GITHUB"; EMAIL_PASSWORD: "EMAIL_PASSWORD"} as const}
 */
export const UserLoginType = {
  GOOGLE: "GOOGLE",
  GITHUB: "GITHUB",
  EMAIL_PASSWORD: "EMAIL_PASSWORD",
};
export const AvailableSocialLogins = Object.values(UserLoginType);

/**
 * @type {{ ADMIN: "ADMIN"; USER: "USER"} as const}
 */
export const UserRolesEnum = {
  ADMIN: "ADMIN",
  USER: "USER",
};
export const AvailableUserRoles = Object.values(UserRolesEnum);

export const ProductColorsEnum = {
  RED: "RED",
  GREEN: "GREEN",
  BLUE: "BLUE",
  BLACK: "BLACK",
  WHITE: "WHITE",
  YELLOW: "YELLOW",
  PURPLE: "PURPLE",
  ORANGE: "ORANGE",
  PINK: "PINK",
  GRAY: "GRAY",
  BROWN: "BROWN",
  SILVER: "SILVER",
  GOLD: "GOLD",
  TEAL: "TEAL",
  CYAN: "CYAN",
  LIME: "LIME",
  MAGENTA: "MAGENTA",
  INDIGO: "INDIGO",
  LAVENDER: "LAVENDER",
  TURQUOISE: "TURQUOISE",
  PLUM: "PLUM",
  OLIVE: "OLIVE",
  MAROON: "MAROON",
  NAVY: "NAVY",
  TAN: "TAN",
  AQUA: "AQUA",
  BEIGE: "BEIGE",
  CORAL: "CORAL",
  CHOCOLATE: "CHOCOLATE",
  CHARCOAL: "CHARCOAL",
  BRONZE: "BRONZE",
  COPPER: "COPPER",
  CRIMSON: "CRIMSON",
  IVORY: "IVORY",
  KHAKI: "KHAKI",
  MAUVE: "MAUVE",
  SEPIA: "SEPIA",
  VIOLET: "VIOLET",
  LILAC: "LILAC",
  GRASS_GREEN: "GRASS_GREEN",
  SKY_BLUE: "SKY_BLUE",
  SUNSET_ORANGE: "SUNSET_ORANGE",
  LEMON_YELLOW: "LEMON_YELLOW",
  RUBY_RED: "RUBY_RED",
  PEACH: "PEACH",
  ROSE: "ROSE",
  PLATINUM: "PLATINUM",
  LAVENDER_BLUE: "LAVENDER_BLUE",
  MINT_GREEN: "MINT_GREEN",
  STEEL_GRAY: "STEEL_GRAY",
  MANGO: "MANGO",
  OLIVE_GREEN: "OLIVE_GREEN",
  BURGUNDY: "BURGUNDY",
  EGGPLANT: "EGGPLANT",
  PERIWINKLE: "PERIWINKLE",
  SAFFRON: "SAFFRON",
  COBALT_BLUE: "COBALT_BLUE",
  MAHOGANY: "MAHOGANY",
  RUST: "RUST",
  BEETROOT: "BEETROOT",
  CANARY_YELLOW: "CANARY_YELLOW",
};
export const AvailableProductColors = Object.values(ProductColorsEnum);

export const ProductBrandsEnum = {
  // ELECTRONICS - comment for understanding category change for the brand
  APPLE: "APPLE",
  SAMSUNG: "SAMSUNG",
  SONY: "SONY",
  LG: "LG",
  PANASONIC: "PANASONIC",
  TOSHIBA: "TOSHIBA",
  PHILIPS: "PHILIPS",
  HISENSE: "HISENSE",
  TCL: "TCL",
  HAIER: "HAIER",
  XIAOMI: "XIAOMI",
  LENOVO: "LENOVO",

  // FOOD - comment for understanding category change for the brand
  COCA_COLA: "COCA-COLA",
  PEPSI: "PEPSICo",
  NESTLE: "NESTLÉ",
  UNILEVER: "UNILEVER",
  KRAFT_HEINZ: "KRAFT HEINZ",
  MONDELEZ_INTERNATIONAL: "MONDELEZ INTERNATIONAL",
  GENERAL_MILLS: "GENERAL MILLS",
  KELLOGGS: "KELLOGG'S",
  MARS: "MARS",
  ASSOCIATED_BRITISH_FOODS: "ASSOCIATED BRITISH FOODS",
  DANONE: "DANONE",

  // AUTOMOBILES - comment for understanding category change for the brand
  TOYOTA: "TOYOTA",
  VOLKSWAGEN: "VOLKSWAGEN",
  HYUNDAI: "HYUNDAI",
  STELLANTIS: "STELLANTIS",
  GENERAL_MOTORS: "GENERAL MOTORS",
  FORD: "FORD",
  HONDA: "HONDA",
  BMW: "BMW",
  DAIMLER: "DAIMLER",
  NISSAN: "NISSAN",
  RENAULT: "RENAULT",
  TESLA: "TESLA",

  // APPAREL
  NIKE: "NIKE",
  ADIDAS: "ADIDAS",
  PUMA: "PUMA",
  UNDER_ARMOUR: "UNDER ARMOUR",
  ZARA: "ZARA",
  H_AND_M: "H_AND_M",
  UNIQLO: "UNIQLO",
  GAP: "GAP",
  FAST_RETAILING: "FAST RETAILING",
  LVMH: "LVMH",
  KERING: "KERING",

  // FOOTWEAR
  NIKE: "NIKE",
  ADIDAS: "ADIDAS",
  PUMA: "PUMA",
  REEBOK: "REEBOK",
  VANS: "VANS",
  CONVERSE: "CONVERSE",
  NEW_BALANCE: "NEW BALANCE",
  SKECHERS: "SKECHERS",
  ASICS: "ASICS",
  WOLVERINE: "WOLVERINE",
  TIMBERLAND: "TIMBERLAND",

  // HOME_AND_GARDEN
  IKEA: "IKEA",
  HOME_DEPOT: "HOME DEPOT",
  LOWES: "LOWE'S",
  WALMART: "WALMART",
  TARGET: "TARGET",
  AMAZON: "AMAZON",
  WAYFAIR: "WAYFAIR",
  BED_BATH_AND_BEYOND: "BED BATH & BEYOND",
  WILLIAMS_SONOMA: "WILLIAMS-SONOMA",
  MACYS: "MACY'S",
  KOHLS: "KOHL'S",

  // BEAUTY_AND_PERSONAL_CARE
  PROCTER_AND_GAMBLE: "PROCTER & GAMBLE",
  LOREAL: "L'ORÉAL",
  UNILEVER: "UNILEVER",
  COTY: "COTY",
  ESTEE_LAUDER: "ESTÉE LAUDER",
  SHISEIDO: "SHISEIDO",
  JOHNSON_AND_JOHNSON: "JOHNSON & JOHNSON",
  COLGATE_PALMOLIVE: "COLGATE-PALMOLIVE",
  BEIERSDORF: "BEIERSDORF",
  KAO: "KAO",
  AMOREPACIFIC: "AMOREPACIFIC",

  // HEALTH_AND_WELLNESS
  UNITEDHEALTH_GROUP: "UNITEDHEALTH GROUP",
  CVS_HEALTH: "CVS HEALTH",
  WALGREENS_BOOTS_ALLIANCE: "WALGREENS BOOTS ALLIANCE",
  JOHNSON_AND_JOHNSON: "JOHNSON & JOHNSON",
  ABBVIE: "ABBVIE",
  PFIZER: "PFIZER",
  MODERNA: "MODERNA",
  BIONTECH: "BIONTECH",
  ROCHE: "ROCHE",
  NOVARTIS: "NOVARTIS",
  MERCK_AND_CO: "MERCK & CO.",

  // SPORTS_AND_OUTDOORS
  NIKE: "NIKE",
  ADIDAS: "ADIDAS",
  PUMA: "PUMA",
  UNDER_ARMOUR: "UNDER ARMOUR",
  COLUMBIA_SPORTSWEAR: "COLUMBIA SPORTSWEAR",
  DECATHLON: "DECATHLON",
  THE_NORTH_FACE: "THE NORTH FACE",
  PATAGONIA: "PATAGONIA",
  BURTON_SNOWBOARDS: "BURTON SNOWBOARDS",
  OAKLEY: "OAKLEY",
  YETI_COOLERS: "YETI COOLERS",

  // BOOKS AND MEDIA
  AMAZON: "AMAZON",
  PENGUIN_RANDOM_HOUSE: "PENGUIN RANDOM HOUSE",
  HACHETTE_LIVRE: "HACHETTE LIVRE",
  SCHOLASTIC_CORPORATION: "SCHOLASTIC CORPORATION",
  HARPERCOLLINS_PUBLISHERS: "HARPERCOLLINS PUBLISHERS",
  MACMILLAN_PUBLISHERS: "MACMILLAN PUBLISHERS",
  SIMON_AND_SCHUSTER: "SIMON & SCHUSTER",
  BLOOMSBURY_PUBLISHING: "BLOOMSBURY PUBLISHING",

  // McGRAW-HILL EDUCATION
  MCGRAW_HILL_EDUCATION: "MCGRAW-HILL EDUCATION",
  PEARSON_EDUCATION: "PEARSON EDUCATION",
  CENGAGE_LEARNING: "CENGAGE LEARNING",

  // TOYS AND GAMES
  MATTEL: "MATTEL",
  HASBRO: "HASBRO",
  LEGO: "LEGO",
  MGA_ENTERTAINMENT: "MGA ENTERTAINMENT",
  SPIN_MASTER: "SPIN MASTER",
  JAKKS_PACIFIC: "JAKKS PACIFIC",
  BANDAI_NAMCO: "BANDAI NAMCO",
  ELECTRONIC_ARTS: "ELECTRONIC ARTS",
  ACTIVISION_BLIZZARD: "ACTIVISION BLIZZARD",
  TAKE_TWO_INTERACTIVE: "TAKE-TWO INTERACTIVE",
  UBISOFT: "UBISOFT",

  // JEWELRY AND ACCESSORIES
  CARTIER: "CARTIER",
  TIFFANY_AND_CO: "TIFFANY & CO.",
  BULGARI: "BULGARI",
  VAN_CLEEF_AND_ARPELS: "VAN CLEEF & ARPELS",
  ROLEX: "ROLEX",
  OMEGA: "OMEGA",
  PATEK_PHILIPPE: "PATEK PHILIPPE",
  AUDEMARS_PIGUET: "AUDEMARS PIGUET",
  CHOPARD: "CHOPARD",
  GRAFF: "GRAFF",
  BUCCELLATI: "BUCCELLATI",

  // FURNITURE
  IKEA: "IKEA",
  ASHLEY_FURNITURE: "ASHLEY FURNITURE",
  ETHAN_ALLEN: "ETHAN ALLEN",
  RESTORATION_HARDWARE: "RESTORATION HARDWARE",
  CRATE_AND_BARREL: "CRATE & BARREL",
  POTTERY_BARN: "POTTERY BARN",
  WILLIAMSONOMA_HOME: "WILLIAM-SONOMA HOME",
  WEST_ELM: "WEST ELM",
  ARTICLE: "ARTICLE",
  WAYFAIR: "WAYFAIR",

  // PET SUPPLIES
  MARS_PETCARE: "MARS PETCARE",
  NESTLE_PURINA_PETCARE: "NESTLÉ PURINA PETCARE",
  JM_SMUCKER: "J.M. SMUCKER",
  HILLS_PET_NUTRITION: "HILL'S PET NUTRITION",
  BLUE_BUFFALO: "BLUE BUFFALO",
  IAMS: "IAMS",
  EUKANUBA: "EUAKNUBA",
  ROYAL_CANIN: "ROYAL CANIN",
  PURINA: "PURINA",
  PEDIGREE: "PEDIGREE",
  WHISKAS: "WHISKAS",

  // OFFICE SUPPLIES
  AVERY: "AVERY",
  BIC: "BIC",
  CANON: "CANON",
  CASIO: "CASIO",
  CRAYOLA: "CRAYOLA",
  EPSON: "EPSON",
  HP: "HP",
  PAPER_MATE: "PAPER MATE",
  PILOT_PEN: "PILOT PEN",
  SCOTCH: "SCOTCH",

  // MUSIC AND MUSICAL INSTRUMENTS
  UNIVERSAL_MUSIC_GROUP: "UNIVERSAL MUSIC GROUP",
  SONY_MUSIC_ENTERTAINMENT: "SONY MUSIC ENTERTAINMENT",
  WARNER_MUSIC_GROUP: "WARNER MUSIC GROUP",
  FENDER: "FENDER",
  GIBSON: "GIBSON",
  YAMAHA: "YAMAHA",
  ROLAND: "ROLAND",
  KORG: "KORG",
  MAUDIO: "M-AUDIO",
  BEHRINGER: "BEHRINGER",
  SAMSON: "SAMSON",

  // ART AND CRAFT SUPPLIES
  CRAYOLA: "CRAYOLA",
  FABER_CASTELL: "FABER-CASTELL",
  PRISMACOLOR: "PRISMACOLOR",
  ARTEZA: "ARTEZA",
  COPIC: "COPIC",
  WINSOR_AND_NEWTON: "WINSOR & NEWTON",
  LIQUITEX: "LIQUITEX",
  GOLDEN_ARTIST_COLORS: "GOLDEN ARTIST COLORS",
  DALER_ROWNEY: "DALER-ROWNEY",
  CANSON: "CANSON",
  STRATHMORE: "STRATHMORE",

  // BABY AND MATERNITY
  PAMPERS: "PAMPERS",
  HUGGIES: "HUGGIES",
  GERBER: "GERBER",
  ENFAMIL: "ENFAMIL",
  SIMILAC: "SIMILAC",
  GRACO: "GRACO",
  CHICCO: "CHICCO",
  BRITAX: "BRITAX",
  BABYBJORN: "BABYBJÖRN",
  UPPABABY: "UPPABABY",

  // INDUSTRIAL AND SCIENTIFIC
  "3M": "3M",
  BOEING: "BOEING",
  CATERPILLAR: "CATERPILLAR",
  DOW: "DOW",
  DUPONT: "DUPONT",
  GENERAL_ELECTRIC: "GENERAL ELECTRIC",
  GENERAL_MOTORS: "GENERAL MOTORS",
  HONEYWELL: "HONEYWELL",
  IBM: "IBM",
  JOHNSON_AND_JOHNSON: "JOHNSON & JOHNSON",
  LOCKHEED_MARTIN: "LOCKHEED MARTIN",

  // TRAVEL AND LUGGAGE
  AMERICAN_TOURISTER: "AMERICAN TOURISTER",
  DELSEY: "DELSEY",
  EAGLE_CREEK: "EAGLE CREEK",
  SAMSONITE: "SAMSONITE",
  TUMI: "TUMI",
  VICTORINOX: "VICTORINOX",
  AWAY: "AWAY",
  PARAVEL: "PARAVEL",
  ROAM_LUGGAGE: "ROAM LUGGAGE",
  HORIZN_STUDIOS: "HORIZN STUDIOS",
  BEIS: "BEIS",

  // GENERAL
  AMAZON: "AMAZON",
  APPLE: "APPLE",
  ALPHABET: "ALPHABET (GOOGLE)",
  MICROSOFT: "MICROSOFT",
  META: "META (FACEBOOK)",
  WALMART: "WALMART",
  COSTCO: "COSTCO",
  KROGER: "KROGER",
  HOME_DEPOT: "HOME DEPOT",
  LOWES: "LOWE'S",
  TARGET: "TARGET",

  // 🅱️🅱️🅱️🅱️🅱️🅱️🅱️🅱️🅱️🅱️🅱️
  // CLOTHING & ACCESSORIES
  ZARA: "ZARA",
  H_AND_M: "H_AND_M",
  NIKE: "NIKE",
  ADIDAS: "ADIDAS",
  LEVIS: "LEVIS",

  // ELECTRONICS
  APPLE: "APPLE",
  SAMSUNG: "SAMSUNG",
  SONY: "SONY",
  LG: "LG",
  DELL: "DELL",

  // HOME & KITCHEN
  PHILIPS: "PHILIPS",
  PRESTIGE: "PRESTIGE",
  BOMBAY_DYEING: "BOMBAY_DYEING",
  CELLO: "CELLO",
  TUPPERWARE: "TUPPERWARE",

  // BEAUTY & PERSONAL CARE
  L_OREAL: "L_OREAL",
  MAYBELLINE: "MAYBELLINE",
  DOVE: "DOVE",
  NIVEA: "NIVEA",
  OLAY: "OLAY",

  // HEALTH & WELLNESS
  HIMALAYA: "HIMALAYA",
  AMWAY: "AMWAY",
  DABUR: "DABUR",
  PATANJALI: "PATANJALI",
  HEALTHKART: "HEALTHKART",

  // SPORTS & OUTDOORS
  NIKE: "NIKE",
  ADIDAS: "ADIDAS",
  REEBOK: "REEBOK",
  PUMA: "PUMA",
  DECATHLON: "DECATHLON",

  // BOOKS & MEDIA
  PENGUIN_RANDOM_HOUSE: "PENGUIN_RANDOM_HOUSE",
  HARPERCOLLINS: "HARPERCOLLINS",
  SIMON_AND_SCHUSTER: "SIMON_AND_SCHUSTER",
  BLOOMSBURY: "BLOOMSBURY",
  HACHETTE: "HACHETTE",

  // TOYS & GAMES
  LEGO: "LEGO",
  MATTEL: "MATTEL",
  HASBRO: "HASBRO",
  FISHER_PRICE: "FISHER_PRICE",
  BARBIE: "BARBIE",

  // AUTOMOTIVE
  TOYOTA: "TOYOTA",
  FORD: "FORD",
  HONDA: "HONDA",
  BMW: "BMW",
  MERCEDES_BENZ: "MERCEDES_BENZ",

  // PET SUPPLIES
  PEDIGREE: "PEDIGREE",
  ROYAL_CANIN: "ROYAL_CANIN",
  WHISKAS: "WHISKAS",
  HIMALAYA_PET_CARE: "HIMALAYA_PET_CARE",
  PETSAFE: "PETSAFE",

  // JEWELRY & WATCHES
  TANISHQ: "TANISHQ",
  TITAN: "TITAN",
  SWAROVSKI: "SWAROVSKI",
  CARTIER: "CARTIER",
  ROLEX: "ROLEX",

  // GROCERY & GOURMET FOODS
  NESTLE: "NESTLE",
  BRITANNIA: "BRITANNIA",
  PATANJALI: "PATANJALI",
  AMUL: "AMUL",
  CADBURY: "CADBURY",

  // OFFICE & STATIONERY
  FABER_CASTELL: "FABER_CASTELL",
  PARKER: "PARKER",
  CAMLIN: "CAMLIN",
  HP: "HP",
  CANON: "CANON",

  // HOME IMPROVEMENT
  BOSCH: "BOSCH",
  PHILIPS: "PHILIPS",
  GODREJ: "GODREJ",
  HAVELLS: "HAVELLS",
  STANLEY: "STANLEY",

  // TRAVEL & LUGGAGE
  AMERICAN_TOURISTER: "AMERICAN_TOURISTER",
  SAMSONITE: "SAMSONITE",
  VIP_INDUSTRIES: "VIP_INDUSTRIES",
  SAFARI: "SAFARI",
  SKYBAGS: "SKYBAGS",

  // FURNITURE
  IKEA: "IKEA",
  GODREJ_INTERIO: "GODREJ_INTERIO",
  URBAN_LADDER: "URBAN_LADDER",
  PEPPERFRY: "PEPPERFRY",
  NILKAMAL: "NILKAMAL",

  // MOBILE PHONES
  APPLE: "APPLE",
  SAMSUNG: "SAMSUNG",
  ONEPLUS: "ONEPLUS",
  XIAOMI: "XIAOMI",
  REALME: "REALME",

  // LAPTOPS
  APPLE: "APPLE",
  DELL: "DELL",
  HP: "HP",
  LENOVO: "LENOVO",
  ASUS: "ASUS",

  // CAMERAS
  CANON: "CANON",
  NIKON: "NIKON",
  SONY: "SONY",
  FUJIFILM: "FUJIFILM",
  GOPRO: "GOPRO",

  // WATCHES
  TITAN: "TITAN",
  CASIO: "CASIO",
  FOSSIL: "FOSSIL",
  TIMEX: "TIMEX",
  ROLEX: "ROLEX",
};

export const AvailableProductBrands = Object.values(ProductBrandsEnum);

export const ProductTagsEnum = {
  HOT: "HOT",
  POPULAR: "POPULAR",
  NEW: "NEW",
  FEATURED: "FEATURED",
  FAMOUS: "FAMOUS",
  TOP_RATED: "TOP_RATED",
  SALE: "SALE",
  BEST_SELLER: "BEST_SELLER",
  CLEARANCE: "CLEARANCE",
  LIMITED_STOCK: "LIMITED_STOCK",
  TRENDING: "TRENDING",
  SPECIAL_OFFER: "SPECIAL_OFFER",
  SPECIAL: "SPECIAL",
  HOLIDAY: "HOLIDAY",
  BACK_IN_STOCK: "BACK_IN_STOCK",
  EXCLUSIVE: "EXCLUSIVE",
  DISCOUNTED: "DISCOUNTED",
  PRE_ORDER: "PRE_ORDER",
  CUSTOM: "CUSTOM",
  HANDMADE: "HANDMADE",
  ORGANIC: "ORGANIC",
  VEGAN: "VEGAN",
  SUSTAINABLE: "SUSTAINABLE",
  ETHICAL: "ETHICAL",
  LOCAL: "LOCAL",
  RECYCLABLE: "RECYCLABLE",
};

export const AvailableProductTags = Object.values(ProductTagsEnum);

export const ProductCategoryEnum = {
  ELECTRONICS: "ELECTRONICS",
  FOOD: "FOOD",
  AUTOMOBILES: "AUTOMOBILES",
  APPAREL: "APPAREL",
  FOOTWEAR: "FOOTWEAR",
  HOME_AND_GARDEN: "HOME_AND_GARDEN",
  BEAUTY_AND_PERSONAL_CARE: "BEAUTY_AND_PERSONAL_CARE",
  HEALTH_AND_WELLNESS: "HEALTH_AND_WELLNESS",
  SPORTS_AND_OUTDOORS: "SPORTS_AND_OUTDOORS",
  BOOKS_AND_MEDIA: "BOOKS_AND_MEDIA",
  TOYS_AND_GAMES: "TOYS_AND_GAMES",
  JEWELRY_AND_ACCESSORIES: "JEWELRY_AND_ACCESSORIES",
  FURNITURE: "FURNITURE",
  PET_SUPPLIES: "PET_SUPPLIES",
  OFFICE_SUPPLIES: "OFFICE_SUPPLIES",
  MUSIC_AND_MUSICAL_INSTRUMENTS: "MUSIC_AND_MUSICAL_INSTRUMENTS",
  ART_AND_CRAFT_SUPPLIES: "ART_AND_CRAFT_SUPPLIES",
  BABY_AND_MATERNITY: "BABY_AND_MATERNITY",
  INDUSTRIAL_AND_SCIENTIFIC: "INDUSTRIAL_AND_SCIENTIFIC",
  TRAVEL_AND_LUGGAGE: "TRAVEL_AND_LUGGAGE",
  GENERAL: "GENERAL",
  // 😺😺😺😺😺😺😺😺
  CLOTHING_AND_ACCESSORIES: "CLOTHING_AND_ACCESSORIES",
  ELECTRONICS: "ELECTRONICS",
  HOME_AND_KITCHEN: "HOME_AND_KITCHEN",
  BEAUTY_AND_PERSONAL_CARE: "BEAUTY_AND_PERSONAL_CARE",
  HEALTH_AND_WELLNESS: "HEALTH_AND_WELLNESS",
  SPORTS_AND_OUTDOORS: "SPORTS_AND_OUTDOORS",
  BOOKS_AND_MEDIA: "BOOKS_AND_MEDIA",
  TOYS_AND_GAMES: "TOYS_AND_GAMES",
  AUTOMOTIVE: "AUTOMOTIVE",
  PET_SUPPLIES: "PET_SUPPLIES",
  JEWELRY_AND_WATCHES: "JEWELRY_AND_WATCHES",
  GROCERY_AND_GOURMET_FOODS: "GROCERY_AND_GOURMET_FOODS",
  OFFICE_AND_STATIONERY: "OFFICE_AND_STATIONERY",
  HOME_IMPROVEMENT: "HOME_IMPROVEMENT",
  TRAVEL_AND_LUGGAGE: "TRAVEL_AND_LUGGAGE",
  FURNITURE: "FURNITURE",
  MOBILE_PHONES: "MOBILE_PHONES",
  LAPTOPS: "LAPTOPS",
  CAMERAS: "CAMERAS",
  WATCHES: "WATCHES",
};

export const AvailableProductCategories = Object.values(ProductCategoryEnum);

export const BlogCategoryEnum = {
  TECHNOLOGY: "TECHNOLOGY",
  LIFESTYLE: "LIFESTYLE",
  HEALTH: "HEALTH",
  TRAVEL: "TRAVEL",
  FASHION: "FASHION",
  FOOD: "FOOD",
  SPORTS: "SPORTS",
  ENTERTAINMENT: "ENTERTAINMENT",
  BUSINESS: "BUSINESS",
  SCIENCE: "SCIENCE",
  EDUCATION: "EDUCATION",
  FINANCE: "FINANCE",
  ART: "ART",
  BOOKS: "BOOKS",
  MUSIC: "MUSIC",
  PARENTING: "PARENTING",
  DIY: "DIY",
  NEWS: "NEWS",
  ENVIRONMENT: "ENVIRONMENT",
  POLITICS: "POLITICS",
  RELIGION: "RELIGION",
  TRAVEL: "TRAVEL",
  HISTORY: "HISTORY",
  CULTURE: "CULTURE",
  PHILOSOPHY: "PHILOSOPHY",
  SPORTS: "SPORTS",
  TECHNOLOGY: "TECHNOLOGY",
  GAMING: "GAMING",
  HOBBIES: "HOBBIES",
  MENTAL_HEALTH: "MENTAL_HEALTH",
  SELF_IMPROVEMENT: "SELF_IMPROVEMENT",
  CELEBRITIES: "CELEBRITIES",
};

export const AvailableBlogCategories = Object.values(BlogCategoryEnum);
